### ISSUE TITLE
config error when using new version of django

### ISSUE THREAD

**Issue by knitHacker** [MetLifeLegalPlans/willing-zg#54]
When running `zg update` got a `ImproperlyConfigured` error. The issue went away when I reverted to previous version of django.
Version that worked: `3.1.8`
Version that didn't work: `3.2.1`

```
backend_1        | Traceback (most recent call last):
backend_1        |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 244, in create
backend_1        |     app_module = import_module(app_name)
backend_1        |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
backend_1        |     return _bootstrap._gcd_import(name[level:], package, level)
backend_1        |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
backend_1        |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
backend_1        |   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
backend_1        | ModuleNotFoundError: No module named 'zygoat'
backend_1        | 
backend_1        | During handling of the above exception, another exception occurred:
backend_1        | 
backend_1        | Traceback (most recent call last):
backend_1        |   File "./manage.py", line 22, in <module>
backend_1        |     main()
backend_1        |   File "./manage.py", line 18, in main
backend_1        |     execute_from_command_line(sys.argv)
backend_1        |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
backend_1        |     utility.execute()
backend_1        |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
backend_1        |     django.setup()
backend_1        |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
backend_1        |     apps.populate(settings.INSTALLED_APPS)
backend_1        |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
backend_1        |     app_config = AppConfig.create(entry)
backend_1        |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 250, in create
backend_1        |     app_config_class.__qualname__,
backend_1        | django.core.exceptions.ImproperlyConfigured: Cannot import 'zygoat'. Check that 'willing_zg.apps.ZygoatConfig.name' is correct.
```

**Comment by cviveiro** [comment]
https://docs.djangoproject.com/en/3.2/releases/3.2/#automatic-appconfig-discovery

**Comment by cviveiro** [comment]
this definitely works now, i'm gonna close
